version: '3.1'

services:
  mysql:
    image: mysql
    container_name: "mysql-bdt"
    environment:
      MYSQL_ROOT_PASSWORD: "Pr0tett0.98"
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3310:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: "myadmin"
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"

  apache_spark:
    image: httpd
    container_name: "sparkServer"
    ports:
      - 8088:80

#  redis:
#    image: redis
#    container_name: "redis"
#    ports:
#    - 6379:6379
#    volumes:
#      - ./data/redis:/var/lib/redis
#    environment:
#      - REDIS_REPLICATION_MODE=master
#
#  maven:
#    image: maven
#    container_name: "maven"



#  webserver:
#    build: ./dockerfiles
#    restart: always
#    depends_on:
#      - postgres
#    environment:
#      - LOAD_EX=n
#      - EXECUTOR=Local
#    logging:
#      options:
#        max-size: 10m
#        max-file: "3"
#    volumes:
#      - ./dags:/usr/local/airflow/dags
#      # - ./plugins:/usr/local/airflow/plugins
#    ports:
#      - "8080:8080"
#    command: webserver
#    healthcheck:
#      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
#      interval: 30s
#      timeout: 30s
#      retries: 3


