# Spazio abitativo medio

## Import libraries
```{r}

library(dplyr)
library(geojsonio)
library(broom)
library(ggplot2)
library(cowplot)

```

## Import dataset and subset
```{r}
df = read.csv("/Users/elypa/qualita_vita.csv")

df_inter = df[df$INDICATORE == "Spazio abitativo medio",]
```

## Retrieve NUTS2 code from NUTS3 (deleting the last character)
```{r}
df_inter$REGION = gsub('.{1}$', '', df_inter$CODICE.NUTS.3.2021)
```

## Substitute NUTS2 cose with region name
```{r}
df_inter[df_inter$REGION == "ITC1",]$REGION <- "Piemonte"
df_inter[df_inter$REGION == "ITC2",]$REGION <- "Valle d'Aosta/Vallée d'Aoste"
df_inter[df_inter$REGION == "ITC3",]$REGION <- "Liguria"
df_inter[df_inter$REGION == "ITC4",]$REGION <- "Lombardia"
df_inter[df_inter$REGION == "ITH1",]$REGION <- "Trentino-Alto Adige/Südtirol"
df_inter[df_inter$REGION == "ITH2",]$REGION <- "Trentino-Alto Adige/Südtirol"
df_inter[df_inter$REGION == "ITH3",]$REGION <- "Veneto"
df_inter[df_inter$REGION == "ITH4",]$REGION <- "Friuli-Venezia Giulia"
df_inter[df_inter$REGION == "ITH5",]$REGION <- "Emilia-Romagna"
df_inter[df_inter$REGION == "ITI1",]$REGION <- "Toscana"
df_inter[df_inter$REGION == "ITI2",]$REGION <- "Umbria"
df_inter[df_inter$REGION == "ITI3",]$REGION <- "Marche"
df_inter[df_inter$REGION == "ITI4",]$REGION <- "Lazio"
df_inter[df_inter$REGION == "ITF1",]$REGION <- "Abruzzo"
df_inter[df_inter$REGION == "ITF2",]$REGION <- "Molise"
df_inter[df_inter$REGION == "ITF3",]$REGION <- "Campania"
df_inter[df_inter$REGION == "ITF4",]$REGION <- "Puglia"
df_inter[df_inter$REGION == "ITF5",]$REGION <- "Basilicata"
df_inter[df_inter$REGION == "ITF6",]$REGION <- "Calabria"
df_inter[df_inter$REGION == "ITG1",]$REGION <- "Sicilia"
df_inter[df_inter$REGION == "ITG2",]$REGION <- "Sardegna"

```

## Calculate the mean of value for each region and store in a new datases
```{r}
means <- aggregate(VALORE ~ REGION, data = df_inter, FUN = mean)

```

## Barplot
```{r fig.height=11, fig.width=18}
library(hrbrthemes)
par(bg = '#fafafa-')
par(mar = c(12, 5, 5, 5))
my_bar <- barplot(means$VALORE , border=F , names.arg=means$REGION, 
                  las=2, 
                  col= "#17a2b8", 
                  ylim=c(0,110.88) , 
                  ylab="Mq/componenti",
                  main="" )
 
```

